// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = {
  mediaUrl: string;
  appUrl: string;
  siteUrl: string;
  sentryDsn: string | null;
};
