// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberWithUser } from './MemberWithUser';

export type ChannelMembers = {
  members: Array<MemberWithUser>;
  colorList: { [key in string]?: string };
  heartbeatMap: { [key in string]?: bigint };
  selfIndex: number | null;
};
