// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelType } from './ChannelType';

export interface Channel {
  id: string;
  name: string;
  topic: string;
  spaceId: string;
  created: string;
  isPublic: boolean;
  defaultDiceType: string;
  defaultRollCommand: string;
  isDocument: boolean;
  type: ChannelType;
}
