// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from './Channel';
import type { MemberWithUser } from './MemberWithUser';
import type { Space } from './Space';

export type ChannelWithRelated = {
  channel: Channel;
  members: Array<MemberWithUser>;
  space: Space;
  colorList: { [key in string]?: string };
  heartbeatMap: { [key in string]?: bigint };
};
