// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from './Member';

export interface ChannelMembers {
  members: Array<Member>;
  colorList: Record<string, string>;
  heartbeatMap: Record<string, bigint>;
  selfIndex: number | null;
}
