// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMember } from './ChannelMember';
import type { User } from './User';

export interface ChannelMemberWithUser {
  member: ChannelMember;
  user: User;
}
