// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from './Member';

export type ChannelMembers = {
  members: Array<Member>;
  colorList: { [key: string]: string };
  heartbeatMap: { [key: string]: bigint };
  selfIndex: number | null;
};
