// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from './Channel';
import type { ChannelMember } from './ChannelMember';

export type ChannelWithMaybeMember = { channel: Channel; member: ChannelMember | null };
