// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewPost } from './PreviewPost';
import type { StatusKind } from './StatusKind';

export type ClientEvent = { 'type': 'PREVIEW'; preview: PreviewPost } | {
  'type': 'STATUS';
  kind: StatusKind;
  focus: Array<string>;
};
