// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionState = {
  rtt_ms: bigint;
  /**
   * Connection count in the pool.
   *
   * Always 1 if the connection is not pooled.
   */
  count: number;
};
