// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateChannel {
  spaceId: string;
  name: string;
  characterName: string;
  defaultDiceType: string | null;
  isPublic: boolean;
}
