// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateSpace {
  name: string;
  password: string | null;
  description: string;
  defaultDiceType: string | null;
  firstChannelName: string;
}
