// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EditMessage {
  messageId: string;
  name: string | null;
  text: string | null;
  entities: Array<unknown> | undefined;
  inGame: boolean | null;
  isAction: boolean | null;
  mediaId: string | null;
}
