// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelType } from './ChannelType';

export type EditChannel = {
  channelId: string;
  name: string | null;
  topic: string | null;
  defaultDiceType: string | null;
  defaultRollCommand: string | null;
  grantMasters: Array<string>;
  removeMasters: Array<string>;
  isPublic: boolean | null;
  isDocument: boolean | null;
  type: ChannelType | null;
};
