// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EditChannelMember {
  channelId: string;
  characterName: string | null;
  textColor: string | null;
}
