// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EditSpace {
  spaceId: string;
  name: string | null;
  description: string | null;
  defaultDiceType: string | null;
  explorable: boolean | null;
  isPublic: boolean | null;
  allowSpectator: boolean | null;
  grantAdmins: Array<string>;
  removeAdmins: Array<string>;
}
