// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EditUser {
  nickname: string | null;
  bio: string | null;
  avatar: string | null;
}
