// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventBody } from './EventBody';
import type { EventId } from './EventId';

export interface Event {
  mailbox: string;
  id: EventId;
  body: EventBody;
}
