// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventId = {
  /**
   * The timestamp in milliseconds
   * The value will not exceed 2^53 - 1, which is safe for JavaScript
   */
  timestamp: number;
  /**
   * Preserved for future use
   */
  node: number;
  seq: number;
};
