// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpaceWithMember } from './SpaceWithMember';
import type { User } from './User';

export type GetMe = { user: User; settings: unknown; mySpaces: Array<SpaceWithMember> };
