// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelWithMember } from './ChannelWithMember';
import type { SpaceWithMember } from './SpaceWithMember';
import type { User } from './User';

export interface GetMe {
  user: User;
  settings: unknown;
  myChannels: Array<ChannelWithMember>;
  mySpaces: Array<SpaceWithMember>;
}
