// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetMessagesByChannel {
  channelId: string;
  before: number | null;
  limit: number | null;
}
