// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrantOrRevoke } from './GrantOrRevoke';

export interface GrantOrRemoveChannelMaster {
  channelId: string;
  userId: string;
  grantOrRevoke: GrantOrRevoke;
}
