// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetMe } from './GetMe';

export type LoginReturn = { me: GetMe; token: string | null };
