// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Media {
  id: string;
  mimeType: string;
  uploaderId: string;
  filename: string;
  originalFilename: string;
  hash: string;
  size: number;
  description: string;
  source: string;
  created: string;
}
