// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMember } from './ChannelMember';
import type { SpaceMember } from './SpaceMember';
import type { User } from './User';

export interface Member {
  channel: ChannelMember;
  space: SpaceMember;
  user: User;
}
