// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message = {
  id: string;
  senderId: string;
  channelId: string;
  parentMessageId: string | null;
  name: string;
  mediaId: string | null;
  seed: Array<number>;
  inGame: boolean;
  isAction: boolean;
  isMaster: boolean;
  pinned: boolean;
  tags: Array<string>;
  folded: boolean;
  text: string;
  whisperToUsers: Array<string> | null;
  entities: unknown;
  created: string;
  modified: string;
  posP: number;
  posQ: number;
  pos: number;
  /**
   * The color of the message
   *
   * The string is not always a hex color, it can be a preset color name like "preset:orange",
   * or refer to a character's name like "char:DM".
   *
   * If the string contains a semicolon, the second part is for the dark mode.
   */
  color: string;
};
