// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MoveMessageBetween {
  messageId: string;
  range: [[number, number] | null, [number, number] | null];
  channelId: string;
}
