// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewPost = {
  id: string;
  channelId: string;
  name: string;
  mediaId: string | null;
  inGame: boolean;
  isAction: boolean;
  text: string | null;
  clear: boolean;
  entities: Array<unknown>;
  editFor: string | null;
};
