// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewEdit } from './PreviewEdit';

export type Preview = {
  id: string;
  senderId: string;
  channelId: string;
  parentMessageId: string | null;
  name: string;
  mediaId: string | null;
  inGame: boolean;
  isAction: boolean;
  isMaster: boolean;
  clear: boolean;
  text: string | null;
  whisperToUsers: Array<string> | null;
  entities: Array<unknown>;
  pos: number;
  editFor: string | null;
  edit: PreviewEdit | null;
};
