// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Register {
  email: string;
  username: string;
  nickname: string;
  password: string;
}
