// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Space } from './Space';
import type { SpaceMember } from './SpaceMember';
import type { User } from './User';

export interface SpaceWithMember {
  space: Space;
  member: SpaceMember;
  user: User;
}
