// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Space {
  id: string;
  ownerId: string;
  created: number;
  modified: number;
  name: string;
  description: string;
  language: string;
  defaultDiceType: string;
  isPublic: boolean;
  explorable: boolean;
  allowSpectator: boolean;
}
