// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusKind } from './StatusKind';

export type UserStatus = { timestamp: number; kind: StatusKind; focus: Array<string> };
