// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = {
  id: string;
  username: string;
  nickname: string;
  bio: string;
  joined: string;
  avatarId: string | null;
  /**
   * See `Message::color`
   */
  defaultColor: string;
};
