/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/avatars/wrangler.jsonc --include-runtime=false apps/avatars/src/worker-configuration.d.ts` (hash: 0c8cd5ae12176ebab8337cbfef98b516)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
