app = "boluo-server-staging"
primary_region = "nrt"
swap_size_mb = 512

[build]
  image = "ghcr.io/mythal/boluo/server:latest"

[env]
  HOST = '::'
  PORT = "3000"
  PUBLIC_MEDIA_URL = "http://media.dev.boluo.chat"
  S3_BUCKET_NAME = "boluo-development"
  S3_ENDPOINT_URL = "https://9a7f9f4ce45406e8224c0f1e9e6785b5.r2.cloudflarestorage.com"
  RUST_LOG = 'debug'

[http_service]
  auto_start_machines = true
  auto_stop_machines = "stop"
  force_https = false
  internal_port = 3_000
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "20s"
    interval = "20s"
    method = "GET"
    path = "/api/info/healthcheck"
    timeout = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
