[boluo]
pg1-path=/var/lib/postgresql/18/docker
pg1-user=boluo

[global]
log-level-console=info
log-level-file=off
process-max=2
repo1-bundle=y
repo1-path=/boluo
repo1-retention-diff=6
repo1-retention-full=2
repo1-sftp-host=backup.boluo.chat
repo1-sftp-host-fingerprint=f7af9f82b14c261af65afcbcebb3fdcbfd89e98b21709f1b6b801746509a00c5
repo1-sftp-host-key-check-type=fingerprint
repo1-sftp-host-key-hash-type=sha256
repo1-sftp-host-user=pgbackrest
repo1-sftp-private-key-file=/run/pgbackrest/id_rsa_sftp
repo1-type=sftp
start-fast=y

[global:archive-push]
compress-level=3
