[unix_http_server]
file=/run/supervisor.sock
chmod=0700
username=local
password=local

[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock
username=local
password=local

[program:cron]
command=/usr/sbin/cron -f
priority=10
autostart=true
autorestart=true
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:postgres-exporter]
command=/usr/bin/prometheus-postgres-exporter --web.listen-address=0.0.0.0:9187 --config.file=/etc/postgres-exporter.yml
priority=20
autostart=true
autorestart=true
startsecs=1
startretries=10
stopsignal=TERM
stopasgroup=true
killasgroup=true
user=postgres
environment=DATA_SOURCE_NAME="user=%(ENV_POSTGRES_USER)s dbname=%(ENV_POSTGRES_DB)s host=/var/run/postgresql sslmode=disable"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:pgbackrest-exporter]
command=/usr/bin/prometheus-pgbackrest-exporter --web.listen-address=0.0.0.0:9854 --collect.interval=300 --backrest.config=/etc/pgbackrest/pgbackrest.conf --backrest.stanza-include=%(ENV_PGBACKREST_STANZA)s
priority=20
autostart=true
autorestart=true
startsecs=1
startretries=10
stopsignal=TERM
stopasgroup=true
killasgroup=true
user=postgres
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:pgbackrest-check]
command=/usr/local/bin/pgbackrest-check.sh
priority=30
autostart=true
autorestart=false
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
user=postgres
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
