version: '3.8'
services:
  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../apps/server/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  store:
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"

  store-init:
    image: quay.io/minio/mc
    depends_on:
      - store
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add dev http://store:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb dev/boluo;
      /usr/bin/mc anonymous set public dev/boluo;
      exit 0;
      "

volumes:
  postgres-data:
  minio-data:
