name: Generate image tag
description: |
  This action generates a tag for a Docker image based on the branch name.
inputs:
  branch:
    required: false
    description: Branch Name
    default: ${{ github.ref_name }}
outputs:
  tag:
    description: 'Image tag'
    value: ${{ steps.image-tag.outputs.tag }}
runs:
  using: 'composite'
  steps:
    - id: image-tag
      shell: bash
      run: |
        if [[ "${{ inputs.branch }}" == releases/* ]]; then
            echo "tag=production" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.branch }}" == "master" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
        else
            echo "tag=${{ inputs.branch }}" >> $GITHUB_OUTPUT
        fi
