# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boluo-db-staging'
primary_region = 'nrt'
[env]
  POSTGRES_DB = 'boluo'
  POSTGRES_USER = 'boluo'


[build]
  # TODO: Use ghcr.io/mythal/boluo-postgres:latest
  dockerfile = 'Dockerfile'

[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 1
  [[services.ports]]
    port = 5432

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "pgdata"
  destination = "/var/lib/postgresql"
  initial_size = "10gb"
  snapshot_retention = 14
  auto_extend_size_threshold = 90
  auto_extend_size_increment = "1gb"
  auto_extend_size_limit = "64GB"
