name = "boluo-legacy"
compatibility_date = "2025-07-25"
main = "../../packages/backend-proxy/dist/worker.js"

[assets]
  directory = "./dist/"
  not_found_handling = "single-page-application"
  run_worker_first = ["/api/*"]

[vars]
  BACKEND_HOST = "production.boluo.chat"

[env.production.vars]
  BACKEND_HOST = "production.boluo.chat"

[env.staging.vars]
  BACKEND_HOST = "boluo-server-staging.fly.dev"
