matrix:
  PACKAGE:
    - server
    - site
    - legacy
when:
  - event: push
    branch: master
labels:
  backend: local
  distro: nixos
steps:
  - name: build
    image: bash
    commands:
      - nix build '.#${PACKAGE}'
