name: Nix Setup
description: Setup Nix for the workflow
inputs:
  authToken:
    description: Cachix auth token
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # https://github.com/DeterminateSystems/nix-installer-action
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      with:
        diagnostic-endpoint:
        extra-conf: |
          extra-sandbox-paths = /tmp/sccache?

    # https://github.com/cachix/cachix-action
    - name: Set up Cachix
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
      with:
        name: boluo
        # https://github.com/actions/runner/issues/2206#issuecomment-1532246677
        authToken: ${{ inputs.authToken }}

    - name: Show Nix Config
      shell: bash
      run: nix config show
