on:
  pull_request:
  push:
    branches: [master]

jobs:
  lints:
    name: Build
    strategy:
      matrix:
        package:
          - legacy
          - site
          - spa
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/DeterminateSystems/nix-installer-action
      - uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations
      - run: nix build --print-build-logs .#${{ matrix.package }}
