name: Build

on: [push]

jobs:
  cargo:
    env:
      CI: true
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
      postgres:
        image: ghcr.io/mythal/boluo-postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: boluo
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: nix develop --command bash -c "cargo build"

      - name: Init Database
        run: nix develop --command bash -c "cargo run -p manage-cli -- init"
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/boluo

      - name: Test
        run: nix develop --command bash -c "cargo test -p server"
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/boluo
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost/boluo
          SECRET: SOME_SECRET
          REDIS_URL: redis://localhost/
          DEBUG: 1
          PORT: 3000

  node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install -g pnpm && pnpm install

      - name: Check
        run: pnpm check

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
        env:
          CI: true

      - name: Upload boluo-legacy artifacts
        uses: actions/upload-artifact@v3
        with:
          name: boluo-legacy
          path: apps/legacy/dist/
