name: Deploy
on:
  push:
    branches:
      - production
      - master
jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/nixbuild/nix-quick-install-action
      - name: Install Nix
        uses: mythal/nix-quick-install-action@extra-experimental-features
        with:
          extra_experimental_features: ca-derivations
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Show Nix Config
        run: nix config show

      # https://github.com/cachix/cachix-action
      - name: Set up Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
        with:
          name: boluo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Push images
        run: nix run ".#push-images" --accept-flake-config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          BRANCH_NAME: ${{ github.ref_name }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: images
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - run: nix --accept-flake-config --log-format raw -L run .#deploy-server-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEVELOPMENT_TOKEN }}
