name: Release
on:
  push:
    branches:
      - production
      - master
      - main
      - release-*
jobs:
  check:
    uses: ./.github/workflows/check.yml
  images:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - name: Show Nix Config
        run: nix config show

      # https://github.com/cachix/cachix-action
      - name: Set up Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
        with:
          name: boluo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Push images
        run: nix --accept-flake-config --log-format raw -L run ".#push-images"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          BRANCH_NAME: ${{ github.ref_name }}

  staging:
    runs-on: ubuntu-latest
    needs: images
    environment:
      name: staging
      url: https://boluo-site-staging.fly.dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - name: Deploy site to staging
        run: nix --accept-flake-config --log-format raw -L run .#deploy-site-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_TOKEN }}

      - name: Deploy server to staging
        run: nix --accept-flake-config --log-format raw -L run .#deploy-server-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_TOKEN }}

  production:
    runs-on: ubuntu-latest
    needs: staging
    if: github.ref == 'refs/heads/production'
    environment:
      name: production
      url: https://site.boluo.chat
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - name: Deploy site to production
        run: nix --accept-flake-config --log-format raw -L run .#deploy-site-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_TOKEN }}

      - name: Deploy server to production
        run: nix --accept-flake-config --log-format raw -L run .#deploy-server-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_TOKEN }}
