name: Release
on:
  push:
    branches:
      - production
      - master
jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - name: Show Nix Config
        run: nix config show

      # https://github.com/cachix/cachix-action
      - name: Set up Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
        with:
          name: boluo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Push images
        run: nix --accept-flake-config --log-format raw -L run ".#push-images"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          BRANCH_NAME: ${{ github.ref_name }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: images
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - name: Deploy site to staging
        run: nix --accept-flake-config --log-format raw -L run .#deploy-site-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEVELOPMENT_TOKEN }}

      - name: Deploy server to staging
        run: nix --accept-flake-config --log-format raw -L run .#deploy-server-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEVELOPMENT_TOKEN }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/DeterminateSystems/nix-installer-action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093
        with:
          extra-conf: |
            experimental-features = flakes nix-command ca-derivations

      - name: Deploy to staging
        run: nix --accept-flake-config --log-format raw -L run .#deploy-server-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEVELOPMENT_TOKEN }}
